**How to create a Null values in a data**

- None

- np.nan

In [2]:
import numpy as np
import pandas as pd

In [4]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
   'Age':[None,22,24,25],
  'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [10]:
df1.to_csv('data1.csv',index=False)

In [12]:
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
   'Age':[np.nan,22,24,25],
  'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2.to_csv('data2.csv',index=False)

- Categorical data use **None**

- Numerical data use **np.nan**

In [15]:
np.nan+10

nan

In [17]:
None+10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [19]:
df1.isnull()
# isnull = wherever Null value there it display as True

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [21]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [25]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       [None, 24.0, 'Pune'],
       ['Mahesh', 25.0, None]], dtype=object)

**fill the values**

In [28]:
# Random fill
df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2      30  24.0  Pune
3  Mahesh  25.0    30

In [32]:
# Select one column and will with value
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [ ]:
# im not doing inplace=True
df1.fillna(30)
df1['City'].fillna('Delhi')

In [34]:
# pad,ffill,bfill,backfill
# axis=0  axis=1
df1.fillna(method='pad')
df1.fillna(method='pad',axis=1)

df1.fillna(method='bfill')
df1.fillna(method='bfill',axis=1)

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [38]:
df1.fillna(method='pad')

C:\Users\omkar\AppData\Local\Temp\ipykernel_9160\433459684.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

In [36]:
df1.values

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       [None, 24.0, 'Pune'],
       ['Mahesh', 25.0, None]], dtype=object)

In [40]:
df1.fillna(method='pad',axis=1)

C:\Users\omkar\AppData\Local\Temp\ipykernel_9160\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

- mean

- median

- mode

In [45]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

**Situation-1**

In [ ]:
# There is No particular Rule how to fille the missing values
# It is completely based on situation

In [49]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [51]:
d1 # I want to handover this data to my students with not encode

   Gender
0    Male
1  Female
2    None

In [53]:
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

In [55]:
# The student think that I want to fill a missing
# data is numerical : mean
(1+0)/2

0.5

In [ ]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

**situation-2**

In [ ]:
# ML algorithm
# Churn : stay or not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**situation-3**

In [61]:
# No of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**situation-4**

In [66]:
course=['DS','AI','DS','Devops','AI','Devlops','AI']
fee=[30000,2700,30000,22000,3000,22000,np.nan]
pd.DataFrame(zip(course,fee))

# First group by with  course
# then take corresponding course values only

         0        1
0       DS  30000.0
1       AI  27000.0
2       DS  30000.0
3   Devops  22000.0
4       AI  30000.0
5  Devlops  22000.0
6       AI      NaN

**KNNImputer**

- KNN : K-nearest neighbours

- where K is a number

- instaed of taking avg of all the values data

    - first will find the neighbours who are close with missing data 

    - by using Euclidian distance calculation will idenify the neighbour rows

    - suppose k=2 will identify the two closest rows

    - those closest rows values will take it, will calculate the mean

    - finally will fill with the mean

In [71]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),
            columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn

    - impute

        - KNNImputer

In [84]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0

In [82]:
6.0e+04

60000.0